version: "3"

services:
  front:
    depends_on:
      - back
    image: tccgrupo14/seekers-front:latest
    ports:
      - 80:80
    networks:
      - sknet
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any

  back:
    image: tccgrupo14/seekers-back:latest
    ports:
      - 9000:8000
    networks:
      - sknet
    environment:
      - DB_NAME=grupo14
      - DB_USER=grupo14
      - DB_HOST=grupo14.database.windows.net
      - DB_PASSWORD=seekers@urubu123
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any


networks:
  sknet:
    driver: overlay


