version: "3"

services:
  front:
    depends_on:
      - back
    image: tccgrupo14/seekers-front:latest
    ports:
      - 8080:80
    networks:
      - sknet
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any

  back:
    image: tccgrupo14/seekers-back:aa52f53285329bfcd424c015fde629f3a7de9aa4
    ports:
      - 9000:8000
    networks:
      - sknet
    environment:
      - DB_NAME=grupo14
      - DB_USER=grupo14
      - DB_HOST=grupo14.database.windows.net
      - DB_PASSWORD=seekers@urubu123
    deploy:
      replicas: 6
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any

networks:
  sknet:
    driver: overlay
    attachable: true
